"""
view_profile.py

Quick helper: print the full extracted profile for ONE resume as JSON,
without re-running the whole batch. Reads from parser_evaluation_v2.json
(generated by run_evaluation.py), so run that first.

Usage:
    python3 view_profile.py Resume_25.pdf
    python3 view_profile.py          (lists all available resume filenames)
"""

import json
import sys


def main():
    try:
        with open("parser_evaluation_v2.json", "r", encoding="utf-8") as f:
            profiles = json.load(f)
    except FileNotFoundError:
        print("parser_evaluation_v2.json not found. Run this first:")
        print("  python3 run_evaluation.py resumes")
        return

    if len(sys.argv) < 2:
        print("Available resumes:")
        for name in profiles:
            print(f"  {name}")
        print("\nRun again as: python3 view_profile.py <filename>")
        return

    filename = sys.argv[1]
    if filename not in profiles:
        print(f"'{filename}' not found. Available:")
        for name in profiles:
            print(f"  {name}")
        return

    print(json.dumps(profiles[filename], indent=2))


if __name__ == "__main__":
    main()
